dockerfile
malawi-ministry-of-health-dhd/hmis-interop pull request #1
Opened 2021-04-22 09:34 UTC by Loui4

2021-04-22 09:40 UTC, bwighane requested changes

2021-04-22 09:40 UTC, bwighane commented on dockerfile
> +FROM node:14 as builder
How big is the image after building this. I highly recommend looking into the alpine distro's where possible. This looks great

2021-04-22 09:46 UTC, brett-onions approved these changes
Looks Good, I like the inclusion of the build-time variables. Circumvents the need to create a docker-compose file.

2021-04-22 11:58 UTC, Loui4 commented on dockerfile
> +FROM node:14 as builder
thanks, am using alpine distro for the final image

2021-04-23 07:19 UTC, bwighane approved these changes

2021-04-23 07:19 UTC, merged